basePath: /api/v1
definitions:
  domain.Cliente:
    properties:
      email:
        type: string
      id:
        type: string
      nome:
        type: string
      telefone:
        type: string
    type: object
  domain.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  domain.Prestador:
    properties:
      ativo:
        type: boolean
      email:
        type: string
      id:
        type: string
      nome:
        type: string
      servicosIDs:
        items:
          type: string
        type: array
      telefone:
        type: string
    type: object
  request.ClienteRequest:
    properties:
      email:
        type: string
      nome:
        type: string
      telefone:
        type: string
    required:
    - nome
    - telefone
    type: object
  request.PrestadorRequest:
    properties:
      email:
        type: string
      nome:
        type: string
      servicos_ids:
        items:
          type: string
        type: array
      telefone:
        type: string
    required:
    - nome
    - servicos_ids
    - telefone
    type: object
host: localhost:8080
info:
  contact: {}
  description: API para gestão de clientes e serviços.
  title: API de Agendamentos
  version: "1.0"
paths:
  /clientes:
    post:
      consumes:
      - application/json
      description: Recebe dados de nome, email e telefone para registrar um novo cliente.
      parameters:
      - description: Dados do Cliente
        in: body
        name: cliente
        required: true
        schema:
          $ref: '#/definitions/request.ClienteRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Cliente criado com sucesso
          schema:
            $ref: '#/definitions/domain.Cliente'
        "400":
          description: Dados inválidos (erro de validação do binding)
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "409":
          description: Cliente já cadastrado (Email ou Telefone já existe)
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Falha na persistência de dados ou erro interno
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Cadastra um novo cliente
      tags:
      - Clientes
  /clientes/{id}:
    get:
      consumes:
      - application/json
      description: Retorna os dados de um cliente específico usando seu ID.
      parameters:
      - description: ID do Cliente
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Cliente encontrado com sucesso
          schema:
            $ref: '#/definitions/domain.Cliente'
        "400":
          description: 'ID inválido fornecido (ex: formato incorreto se houver validação
            de formato de ID)'
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "404":
          description: Cliente não encontrado
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Erro interno do servidor ou falha de infraestrutura
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Busca um cliente pelo ID
      tags:
      - Clientes
  /prestadores:
    post:
      consumes:
      - application/json
      description: Recebe os dados necessários para registrar um novo prestador.
      parameters:
      - description: Dados do Prestador
        in: body
        name: prestador
        required: true
        schema:
          $ref: '#/definitions/request.PrestadorRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Prestador criado com sucesso
          schema:
            $ref: '#/definitions/domain.Prestador'
        "400":
          description: Dados inválidos (erro de validação do binding)
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "409":
          description: Prestador já cadastrado ou conflito de dados
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Falha na persistência de dados ou erro interno
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Cadastra um novo prestadores
      tags:
      - Prestadores
swagger: "2.0"
